repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
  hooks:
    - id: terraform_docs
      args:
      - "--args=--sort-by required"
    - id: terraform_fmt
    - id: terraform_validate
      args:
      - "--hook-config=--retry-once-with-cleanup=true"
    - id: terraform_providers_lock
      args:
      - "--hook-config=--mode=always-regenerate-lockfile"
    - id: terraform_tflint
      args:
        - --args=--disable-rule=terraform_unused_declarations #FIXME - remove when we go to PROD
    # - id: terraform_tfsec
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
      exclude_types:
        - "yaml"
        - "svg"
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: check-json
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.19.1
  hooks:
    - id: gitlint
      args: [--msg-filename]
      stages: [commit-msg]
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.2
  hooks:
    - id: gitleaks
